# Generated by Django 5.2.4 on 2026-02-26 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('type_document', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soma.faculte')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soma.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAcademique',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exercice_traite', models.CharField(max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('nombre_pages_total', models.PositiveIntegerField(default=0)),
                ('fichier_pdf', models.FileField(upload_to='documents_pdf/')),
                ('page_de_garde', models.ImageField(upload_to='couvertures/')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soma.departement')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soma.etudiant')),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soma.faculte')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soma.niveau')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soma.faculte'),
        ),
        migrations.CreateModel(
            name='HistoriqueConsultation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_lecture', models.DateTimeField(auto_now=True)),
                ('page_actuelle', models.PositiveIntegerField(default=1)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soma.documentacademique')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soma.etudiant')),
            ],
            options={
                'unique_together': {('etudiant', 'document')},
            },
        ),
    ]
