# Generated by Django 5.2.4 on 2026-02-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soma', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoriqueConsultation',
            new_name='Historique',
        ),
    ]
