# Generated by Django 5.2.4 on 2026-02-26 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soma', '0002_rename_historiqueconsultation_historique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentacademique',
            name='faculte',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='faculte',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='departement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='soma.departement'),
            preserve_default=False,
        ),
    ]
