# Generated by Django 5.2.4 on 2026-02-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soma', '0003_remove_documentacademique_faculte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentacademique',
            name='page_de_garde',
        ),
        migrations.AlterField(
            model_name='documentacademique',
            name='nombre_pages_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
