# Generated by Django 5.2.4 on 2026-02-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soma', '0004_remove_documentacademique_page_de_garde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacademique',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
