# Generated by Django 5.2.4 on 2026-02-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soma', '0005_documentacademique_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='faculte',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='soma.faculte'),
            preserve_default=False,
        ),
    ]
